### ISSUE TITLE
Unable to find rodalies train from Clot-Aragó to El Prat-Terminal T2-C (Barcelona, ES)

### ISSUE THREAD

**Issue by Freso** [schildbach/public-transport-enabler#142]
Using Transportr I was trying to look up times for getting to the airport tomorrow morning. I live close to the Clot-Aragó metro + renfe/rodalies station, so the easiest way for me to get to the airport is to take the train from Clot directly to the airport, but Transportr seems unable to find such a connection.

Entered information in Transportr:
Dept.: "Aragó-Metro Clot" (station)
Arr.: "Aeroport -Terminal T2 C" (station)
Arrival @ 7:45 2017-02-14
Allowed options: High-Speed Train, Regional Train, Suburban Train, Tram, Cablecar

Adding "Subways" to allowed options enables Transportr to find connections, so the end points seem to be valid.

Checking the Rodalies website shows that there are indeed trains going every half an hour from Clot-Aragó though: http://www.renfe.com/EN/viajeros/cercanias/barcelona/index.html

**Comment by grote** [comment]
This data comes from Navitia and is probably expired. You can check the expiry dates here: https://navitia.opendatasoft.com/explore/dataset/es/table/?sort=type_file

They have a mailing list to discuss these things and there this thread is probably relevant: https://groups.google.com/d/msg/navitia/W_74FRk57x8/T_Df1CHrBAAJ

**Comment by tenminutemail** [comment]
Hi @Freso 

Currently, there are various issues about the public transport data available for Barcelona:

- In the Barcelona metropolitan area only FGC (trains running from Barcelona to Terrassa and Sabadell) and TMB (metro lines in Barcelona and buses in and around the city) provide GTFS data. So that is the only data that can be included into Navitia. Right now the TMB data is lacking all information on buses in the city, but Navitia is trying to solve this issue. Have a look at the last link @grote posted.

- There is no open data available for the TRAM lines operated in Barcelona and neither is there any open data available for the Rodalies train network (commuter trains). The train you wanted to look up is a Rodalies line so there is no information available at all and hence transportr can only show the metro connection (operated by TMB) to the airport.

- Contacting the regional government (they operate Rodalies together with Renfe) to make them open up the GTFS data (which is integrated into Google Maps for quite some time now) didn't really bring about a positive answer. It doesn't look like they're going to release this data anytime soon.

- There is a powerful public transport tool which contains timetables for all of Catalonia (and therefore also for Barcelona including Rodalies, as well as TRAM): http://mou-te.gencat.cat/portada-moute.html#/en/portada. If someone has the knowledge and time to implement the API of this portal into public transport enabler and transportr, he or she will be more than welcome. The legal note of the web page permits the reutilisation of the data, so this could be a good solution to complete the missing public transport data for Barcelona.

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
