### ISSUE TITLE
Add data for Adelaide, South Australia

### ISSUE THREAD

**Issue by Qwertie-** [schildbach/public-transport-enabler#152]
The data is available in https://navitia.opendatasoft.com/explore/dataset/au/table/?sort=type_file but I don't have enough knowledge of java to add it in myself. 

I have also added a $10 bounty for anyone who gets this working https://www.bountysource.com/issues/42912705-add-data-for-adelaide-south-australia

**Comment by Qwertie-** [comment]
Is this closed by https://github.com/schildbach/public-transport-enabler/commit/973a9d56689321b42b2a1e50c74c8778d7d0694c ?

**Comment by schildbach** [comment]
Good question. @pserwylo, do you know?

**Comment by grote** [comment]
If the data is part of the navitia `au` region, it should be available with the new provider.

**Comment by pserwylo** [comment]
This is indeed covered by the Australia provider. @schildbach - this issue can be closed now I believe.

**Comment by pserwylo** [comment]
@Qwertie- would love to get any feedback on the Adelaide transport system and this library. Happy to help straighten it up if anything is a bit off. It is a little tricky because you end up searching all of Australia, instead of just Adelaide, but hopefully I'll be able to help get that working better over time.

**Comment by Qwertie-** [comment]
@pserwylo How would I go about testing this? When I checked the data wasn't in the Transportr app yet. 
Maybe @grote might know more about this?

**Comment by pserwylo** [comment]
I've submitted a patch to Transportr, so it will be available in the next preview release from @grote's F-Droid repository.

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
