### ISSUE TITLE
Add label key support to AbstractNavitiaProvider

### ISSUE THREAD

**Issue by ialokim** [schildbach/public-transport-enabler#186]
Navitia's [`stop_point` and `stop_area`](http://doc.navitia.io/#public-transport-objects) present the key `label` apart of the `name` where it combines the stop and the city name as explained [here](https://github.com/grote/osm2gtfs/issues/108#issuecomment-355777069).

I think it would be very easy to implement support for this tag inside `AbstractNavitiaProvider.java`, but before making a PR I wanted to discuss it here. I think it would be very useful for all Navitia providers, but if there are down points, we could include it in an custom provider.

**Comment by ialokim** [comment]
Looking at the code, it seems PTE already combines the stop and the city name, but only in some cases (hardcoded, in German language), see [here](https://github.com/schildbach/public-transport-enabler/blob/master/enabler/src/de/schildbach/pte/dto/Location.java#L139).

Perhaps we should think about a more general approach of combining both inside PTE while not using the `label` field as suggested by @grote [here](/grote/oms2gtfs/issues/108).

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
