### ISSUE TITLE
Error retrieving directions

### ISSUE THREAD

**Issue by zecamigo** [schildbach/public-transport-enabler#265]
Thanks for adding Lisbon data source!

By the way the link for reporting errors is broken missing a /

Got an terror getting directions. GPS was off.

java.lang.IllegalArgumentException: Unhandled error id: no_origin
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1066)
de.schildbach.pte.AbstractNetworkProvider.queryTrips(AbstractNetworkProvider.java:92)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:103)

![Screenshot_20190509-000015](https://user-images.githubusercontent.com/7470175/57414053-804a0300-71ee-11e9-8b5d-7652c1d17758.png)

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
