### ISSUE TITLE
Add support for Estonia

### ISSUE THREAD

**Issue by mvglasow** [schildbach/public-transport-enabler#274]
Navitia has GTFS data for public transport in Estonia. See: https://navitia.opendatasoft.com/explore/dataset/ee/information/. Would be nice to see support for that.

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
