### ISSUE TITLE
IT: NO_TRIPS

### ISSUE THREAD

**Issue by jpsimas** [schildbach/public-transport-enabler#291]
### Query
- NetworkId: `IT`
- From: `Location{STATION, stop_area:OPT:Navitia:ITRP-ST0012721243, 45.0692870/7.6663350, place=Torino, name=Torino - Corso Matteotti - Porta Susa Fs Capolinea}`
- Via: `null`
- To: `Location{STATION, stop_area:OPT:Navitia:ITRP-ST0012720601, 45.0262160/7.6565990, place=Torino, name=Torino - Lingotto Fs}`
- Date: `Fri Jan 31 18:09:24 GMT-03:00 2020`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
No connections could be found :(
```

### Additional information
Metro routes for Torino are missing

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
