### ISSUE TITLE
Venice search not working ( Unhandled error id: no_destination )

### ISSUE THREAD

**Issue by Stack-it-up** [schildbach/public-transport-enabler#307]
I'm using the [Transportr](https://www.transportr.app/) app and I'm trying to understand why Milan is working and Venice is not. Seems to be related to a bug in this library, could you please check it out? 

I also think the region "Italy" is too big and should be split in smaller areas like Moovit does: I tried messing around so far but I can't understand how Navitia and PTE are communicating. Do you have any docs I could read?

I'm attaching a screenshot of my particular issue.
![immagine](https://user-images.githubusercontent.com/61948994/76782703-fb862900-67b0-11ea-941f-f2177a0d23ae.png)

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
