### ISSUE TITLE
GHANA: java.lang.IllegalArgumentException: Unhandled error message: No region available for the coordinates:-4.096456, 5.363207

### ISSUE THREAD

**Issue by monbus225** [schildbach/public-transport-enabler#308]
### Query
- NetworkId: `GHANA`
- From: `Location{ADDRESS, 5.3632070/-4.0964560, place=Abidjan, name=Rue S155 Rue S155}`
- Via: `null`
- To: `Location{STATION, stop_area:accra:SA5113124879, 5.6992330/-0.2058080, name=Abidjan Junction}`
- Date: `Sun Mar 29 07:08:47 GMT 2020`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error message: No region available for the coordinates:-4.096456, 5.363207
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1056)
de.schildbach.pte.AbstractNetworkProvider.queryTrips(AbstractNetworkProvider.java:92)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:109)
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
