### ISSUE TITLE
SPAIN: java.lang.IllegalArgumentException: Unhandled error id: no_destination

### ISSUE THREAD

**Issue by pacoriviere** [schildbach/public-transport-enabler#310]
### Query
- NetworkId: `SPAIN`
- From: `Location{ADDRESS, 41.3911560/2.1583470, place=Barcelona, name=Carrer d'Enric Granados 42}`
- Via: `null`
- To: `Location{POI, 41.4926820/2.3605840, name=Premià de Mar}`
- Date: `Sat Jun 06 11:37:52 GMT+02:00 2020`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error id: no_destination
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1060)
de.schildbach.pte.AbstractNetworkProvider.queryTrips(AbstractNetworkProvider.java:92)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:109)
```

### Additional information
[Please modify this part]

**Comment by pespin** [comment]
Same exception as seen in Transportr:
![exception](https://user-images.githubusercontent.com/1515985/133687188-30030038-d146-4c92-9f98-735dbdeff2cb.png)

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
