### ISSUE TITLE
IT: java.lang.IllegalArgumentException: Unhandled error id: no_origin_nor_destination

### ISSUE THREAD

**Issue by PaperJack315** [schildbach/public-transport-enabler#322]
### Query
- NetworkId: `IT`
- From: `Location{ADDRESS, 43.7179980/10.9305080, place=Empoli, name=Via Luigi Lazzeri 53}`
- Via: `null`
- To: `Location{ADDRESS, 43.6533380/10.9444660, place=Castelfiorentino, name=Via Vittorio Niccoli}`
- Date: `Wed Aug 05 10:26:50 GMT+02:00 2020`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error id: no_origin_nor_destination
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1060)
de.schildbach.pte.AbstractNetworkProvider.queryTrips(AbstractNetworkProvider.java:92)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:109)
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
