### ISSUE TITLE
BRAZIL: java.lang.IllegalArgumentException: Unhandled error id: no_origin_nor_destination

### ISSUE THREAD

**Issue by dragontarie** [schildbach/public-transport-enabler#340]
### Query
- NetworkId: `BRAZIL`
- From: `Location{ADDRESS, -23.5371150/-46.6772150, place=São Paulo, name=Rua Iperoig}`
- Via: `null`
- To: `Location{POI, -7.9340060/-34.8684070, name=Paulista}`
- Date: `Sat Nov 21 10:15:00 GMT-03:00 2020`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error id: no_origin_nor_destination
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1060)
de.schildbach.pte.AbstractNetworkProvider.queryTrips(AbstractNetworkProvider.java:92)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:109)
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
