### ISSUE TITLE
SPAIN: NO_TRIPS

### ISSUE THREAD

**Issue by TokyoghoulEs** [schildbach/public-transport-enabler#342]
### Query
- NetworkId: `SPAIN`
- From: `Location{ADDRESS, 40.5443290/-3.6402640, place=Alcobendas, name=Calle de la Constitución 82}`
- Via: `null`
- To: `Location{STATION, stop_area:OMD:Navitia:646, 40.3779000/-3.7838100, place=Madrid, name=Base Aérea Cuatro Vientos}`
- Date: `Fri Dec 04 13:47:24 GMT+01:00 2020`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, BUS]`
- Optimize for: `LEAST_CHANGES`
- Walk Speed: `NORMAL`

### Error
```
No se pudieron encontrar trayectos, :(
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
