### ISSUE TITLE
ONTARIO: NO_TRIPS

### ISSUE THREAD

**Issue by jelbana** [schildbach/public-transport-enabler#354]
### Query
- NetworkId: `ONTARIO`
- From: `Location{STATION, stop_area:OON:Navitia:14188, 43.7043140/-79.3983080, place=Old Toronto, name=EGLINTON STATION}`
- Via: `null`
- To: `Location{STATION, stop_area:OON:Navitia:9227, 43.6456520/-79.3792100, place=Old Toronto, name=UNION STATION}`
- Date: `Sun Jan 31 12:13:09 EST 2021`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
No connections could be found :(
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
