### ISSUE TITLE
AbstractNavitiaProvider: Trip Sorting Issues

### ISSUE THREAD

**Issue by grote** [schildbach/public-transport-enabler#38]
Hi @aelkhour,

when querying for trips with dep=false for "date is arrival time", then the trips are given in reverse chronological order with latest tips first and earliest at the end.

Similar, when querying for earlier trips with queryMoreTrips, then the earlier trips are also in reverse chronological order.

I'm not sure whether providers are supposed to give data in the proper order or whether its the consumer who is responsible for ordering correctly. Maybe @schildbach can shed some light on that. I would of course appreciate to get the correct trip order from PTE without having to re-sort trips myself chronologically.

**Comment by schildbach** [comment]
I used to rely on the ordering as delivered by the server. However, it never worked 100% because with Hafas it can happen if you query for more trips you'll get a stray trip that would sort into the previous query. So I started sorting in the app anyway.

I would suggest keeping the adapters simple and just return trips as received from the server.

**Comment by grote** [comment]
Alright, I take care of this in Liberario now. So this issue can be closed.
