### ISSUE TITLE
Random error when creating a trip if a state is not supported

### ISSUE THREAD

**Issue by d4f5409d** [schildbach/public-transport-enabler#380]
OxygenOS, Android 11
OnePlus 8
Source: F-Droid app store

Error:
java.lang.IllegalArgumentException: Unhandled error id: no_origin
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1065)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
