### ISSUE TITLE
BRITISHCOLUMBIA: java.lang.IllegalArgumentException: Unhandled error id: no_origin_nor_destination

### ISSUE THREAD

**Issue by anibyl** [schildbach/public-transport-enabler#397]
### Query
- NetworkId: `BRITISHCOLUMBIA`
- From: `Location{POI, 49.2425730/-123.1088150, place=Vancouver, name=Queen Elizabeth Park}`
- Via: `null`
- To: `Location{POI, 49.2792720/-123.1155830, place=Vancouver, name=Vancouver Public Library}`
- Date: `Wed Sep 01 04:51:08 PDT 2021`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error id: no_origin_nor_destination
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1065)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
No matter what origin or destination I choose, I always get this exception.

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
