### ISSUE TITLE
IT: java.lang.IllegalArgumentException: Unhandled error id: no_destination

### ISSUE THREAD

**Issue by woheller69** [schildbach/public-transport-enabler#405]
### Query
- NetworkId: `IT`
- From: `Location{ADDRESS, 45.8745460/10.8775910, place=Trentino-Alto Adige/Südtirol, name=Via Strada Granda 62/64}`
- Via: `null`
- To: `Location{POI, 46.4132590/11.2462020, name=Kaltern an der Weinstraße - Caldaro sulla Strada del Vino}`
- Date: `Tue Sep 21 11:30:00 GMT+02:00 2021`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error id: no_destination
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1065)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
[Please modify this part]

**Comment by woheller69** [comment]
Probably because the destination is not weithin the supported area. But maybe that should not produce an exception...

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
