### ISSUE TITLE
Error in Transportr (When I try to find a route)

### ISSUE THREAD

**Issue by goliv04053** [schildbach/public-transport-enabler#409]
java.lang.IllegalArgumentException: Unhandled error id: no_origin_nor_destination
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1065)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)

Android 10
Samsung Galaxy A11

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.

**Comment by goliv04053** [comment]
@schildbach Thanks. Not related to this topic but I want to help to add new routes/bus info but I don't know how to report here. How can I proceed? 

I have the links to the websites who have the information. I'm not a programmer.
