### ISSUE TITLE
when from <place> to <place> with same place an error is thrown

### ISSUE THREAD

**Issue by Amiralgaby** [schildbach/public-transport-enabler#411]
### Query
- NetworkId: `FRANCESOUTHEAST`
- From: `Location{POI, 45.7774550/3.0819430, name=Clermont-Ferrand}`
- Via: `null`
- To: `Location{POI, 45.7774550/3.0819430, name=Clermont-Ferrand}`
- Date: `Thu Oct 07 08:25:11 GMT+02:00 2021`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
de.schildbach.pte.exception.BlockedException: https://api.navitia.io/v1/coverage/fr-se/journeys?from=3.081943%3B45.777455&to=3.081943%3B45.777455&datetime=20211007T082511&datetime_represents=departure&min_nb_journeys=6&depth=0&walking_speed=1.12
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:284)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:205)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:198)
```

### Additional information
Same place == error

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
