### ISSUE TITLE
FRANCESOUTHEAST: java.lang.IllegalArgumentException: Unhandled error id: no_origin

### ISSUE THREAD

**Issue by temsa** [schildbach/public-transport-enabler#429]
### Query
- NetworkId: `FRANCESOUTHEAST`
- From: `Location{POI, 45.9637000/5.1900100, name=Crans}`
- Via: `null`
- To: `Location{ADDRESS, 45.7542940/4.8825770, place=Lyon, name=Route de Genas 76}`
- Date: `Wed Dec 08 23:50:08 GMT+01:00 2021`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error id: no_origin
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1065)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
