### ISSUE TITLE
ONTARIO: java.lang.IllegalArgumentException: Unhandled error id: no_destination

### ISSUE THREAD

**Issue by ImranR98** [schildbach/public-transport-enabler#431]
### Query
- NetworkId: `ONTARIO`
- From: `Location{ADDRESS, 43.8501480/-79.4914790, place=Vaughan, name=Pullman Road 42}`
- Via: `null`
- To: `Location{POI, 43.6601980/-79.3797410, place=Old Toronto, name=Ryerson University}`
- Date: `Sat Dec 11 18:41:01 EST 2021`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error id: no_destination
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1065)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
Not sure what's causing this. There is definitely a valid route between these 2 places and the company does provide schedule data in the google maps format iirc.

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
