### ISSUE TITLE
FRANCENORTHEAST: java.lang.IllegalArgumentException: Unhandled error id: no_destination

### ISSUE THREAD

**Issue by Massedil** [schildbach/public-transport-enabler#444]
### Query
- NetworkId: `FRANCENORTHEAST`
- From: `Location{STATION, stop_area:STE:SA:OCE87113001, 48.8767420/2.3584240, place=Quartier Saint-Vincent-de-Paul, name=Paris Est}`
- Via: `null`
- To: `Location{POI, 50.5621610/3.0831300, place=Avelin, name=Aéroport International de Lille - Lesquin}`
- Date: `Tue Feb 01 14:32:32 GMT+01:00 2022`
- Departure: `false`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error id: no_destination
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1065)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
