### ISSUE TITLE
SPAIN: No train stations marked in south Barcelona

### ISSUE THREAD

**Issue by davidfromtheworld** [schildbach/public-transport-enabler#455]
Hi, I'm using the Transportr ap and pI'm trying to route a trip from Vilanova i la Geltrú station in south Barcelona, but there is no option to select the actual station, only the village, and when I try to route it to Barcelona Sants, which is marked as a station, it throws this error.:

java.lang.IllegalArgumentException: Unhandled error id: no_origin
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1065)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)

I've seen that other stations in the area are also not marked. The Transportr app says to report the error here directly :/

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
