### ISSUE TITLE
ONTARIO: java.lang.IllegalArgumentException: Unhandled error message: The region ca-on doesn't exists

### ISSUE THREAD

**Issue by Hate9** [schildbach/public-transport-enabler#460]
### Query
- NetworkId: `ONTARIO`
- From: `Location{ADDRESS, 43.4280840/-80.4276630, place=Kitchener, name=Morgan Avenue 191}`
- Via: `null`
- To: `Location{ADDRESS, 43.4516360/-80.4874880, place=Kitchener, name=Queen Street North 57}`
- Date: `Mon Mar 21 12:23:21 EDT 2022`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_CHANGES`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error message: The region ca-on doesn't exists
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1061)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
[Please modify this part]

**Comment by brandondasilva** [comment]
I'm also experiencing this issue for the ca-on region for all available transit providers

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
