### ISSUE TITLE
Exception output while having same origin and destination

### ISSUE THREAD

**Issue by d-faure** [schildbach/public-transport-enabler#466]
### Query
- NetworkId: `FRANCENORTHEAST`
- From: `Location{POI, 47.5837520/6.8956390, place=Meroux, name=La Jonxion}`
- Via: `null`
- To: `Location{POI, 47.5837520/6.8956390, place=Meroux, name=La Jonxion}`
- Date: `Mon May 02 08:15:46 GMT+02:00 2022`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
de.schildbach.pte.exception.BlockedException: https://api.navitia.io/v1/coverage/fr-ne/journeys?from=6.895639%3B47.583752&to=6.895639%3B47.583752&datetime=20220502T081546&datetime_represents=departure&min_nb_journeys=6&depth=0&walking_speed=1.12
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:284)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:205)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:198)
```

### Additional information
IMHO, no request should be done in this case.

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
