### ISSUE TITLE
BRAZIL: java.lang.IllegalArgumentException: Unhandled error id: no_origin_nor_destination

### ISSUE THREAD

**Issue by M4skid** [schildbach/public-transport-enabler#470]
### Query
- NetworkId: `BRAZIL`
- From: `Location{POI, -23.5253530/-46.6642090, place=São Paulo, name=65 - Terminal Barra Funda (448)}`
- Via: `null`
- To: `Location{ADDRESS, -23.4960110/-46.6220900, place=São Paulo, name=Rua Doutor Zuquim}`
- Date: `Mon May 16 14:36:55 GMT-03:00 2022`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error id: no_origin_nor_destination
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1065)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```#438

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
