### ISSUE TITLE
SPAIN: java.lang.IllegalArgumentException: Unhandled error id: no_origin_nor_destination

### ISSUE THREAD

**Issue by Iey4iej3** [schildbach/public-transport-enabler#474]
### Query
- NetworkId: `SPAIN`
- From: `Location{POI, 41.3079660/2.0873560, place=el Prat de Llobregat, name=Aeroport Barcelona - el Prat Josep Tarradellas}`
- Via: `null`
- To: `Location{ADDRESS, 41.5128030/2.1321230, place=Barberà del Vallès, name=Carrer de Marie Curie}`
- Date: `Sat Jun 04 10:40:17 GMT+02:00 2022`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error id: no_origin_nor_destination
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1065)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
Error for Spain

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
