### ISSUE TITLE
SPAIN: java.lang.IllegalArgumentException: Unhandled error id: no_destination

### ISSUE THREAD

**Issue by uwealtmann** [schildbach/public-transport-enabler#475]
### Query
- NetworkId: `SPAIN`
- From: `Location{ADDRESS, 41.3789170/2.1740320, place=Barcelona, name=Carrer Nou de la Rambla 12}`
- Via: `null`
- To: `Location{POI, 41.4123870/2.1542750, place=Barcelona, name=Parc Guell}`
- Date: `Tue Jun 07 10:23:16 GMT+02:00 2022`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error id: no_destination
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1065)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
[Please modify this part]
Looking for "Parc Güell" in Barcelona

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
