### ISSUE TITLE
FRANCENORTHWEST: UNKNOWN_FROM

### ISSUE THREAD

**Issue by leg7** [schildbach/public-transport-enabler#488]
### Query
- NetworkId: `FRANCENORTHWEST`
- From: `Location{STATION, stop_area:OAN:SA:Navitia:IUT, 47.4802630/-0.6024720, place=Belle-Beille, name=IUT}`
- Via: `null`
- To: `Location{STATION, stop_area:OAN:Navitia:BREMON-E, 47.4659690/-0.5592970, place=Centre Ville - La Fayette - Eblé, name=Gares Bremont}`
- Date: `Tue Sep 13 16:51:12 GMT+02:00 2022`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
Could not find the 'from' location. Please try another one.
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
