### ISSUE TITLE
VRS: java.net.UnknownHostException: Unable to resolve host "android.vrsinfo.de": No address associated with hostname

### ISSUE THREAD

**Issue by phyk** [schildbach/public-transport-enabler#506]
### Query
- NetworkId: `VRS`
- Via: `null`
- Date: `Thu Dec 22 22:01:57 GMT+01:00 2022`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_CHANGES`
- Walk Speed: `NORMAL`

### Error
```
java.net.UnknownHostException: Unable to resolve host "android.vrsinfo.de": No address associated with hostname
java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:157)
java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
java.net.InetAddress.getAllByName(InetAddress.java:1154)
Cause: libcore.io.Linux.android_getaddrinfo(Native Method)
libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:172)
java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:137)
```

### Additional information
Seems to be that VRS is offline for some reason

**Comment by mdyrna** [comment]
Hi @phyk ,

The old endpoint android.vrsinfo.de was indeed removed from DNS.

I originally implemented the VrsProvider because the VRR did not provide real-time information for the VRS region (Cologne, Bonn) at the time. Now it does, so the quickest solution for you and everybody else is to use VrrProvider instead.

@schildbach I created a pull request for VrsProvider to support the new endpoint https://ekap-app.vrs.de/index.php, which the current VRS Android app (https://play.google.com/store/apps/details?id=de.vrsinfo) uses.

**Comment by phyk** [comment]
Thanks @mdyrna
