### ISSUE TITLE
FRANCESOUTHEAST: java.lang.IllegalArgumentException: Unhandled error id: no_destination

### ISSUE THREAD

**Issue by temsa** [schildbach/public-transport-enabler#508]
### Query
- NetworkId: `FRANCESOUTHEAST`
- From: `Location{ADDRESS, 45.7891170/4.8253620, place=Caluire-et-Cuire, name=Rue du Capitaine Ferber 6}`
- Via: `null`
- To: `Location{POI, 45.5513560/4.5867120, place=Saint-Martin-la-Plaine, name=Espace Zoologique de Saint-Martin-La-Plaine}`
- Date: `Wed Dec 28 12:36:47 GMT+01:00 2022`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error id: no_destination
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1065)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
