### ISSUE TITLE
CZECH_REPUBLIC: java.lang.IllegalArgumentException: Unhandled error message: The region cz doesn't exists

### ISSUE THREAD

**Issue by TalOrenshtein** [schildbach/public-transport-enabler#512]
### Query
- NetworkId: `CZECH_REPUBLIC`
- From: `Location{ADDRESS, 50.0796450/14.4300730, place=Hlavní město Praha, name=Nové Město}`
- Via: `null`
- To: `Location{ADDRESS, 50.0831090/14.4243830, place=Hlavní město Praha, name=Václavské náměstí 778/14}`
- Date: `Mon Jan 16 14:02:13 GMT+07:00 2023`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error message: The region cz doesn't exists
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1061)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
Just tried to use Transportr app and got this exception.

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
