### ISSUE TITLE
PARIS: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)

### ISSUE THREAD

**Issue by kir0ul** [schildbach/public-transport-enabler#514]
### Query
- NetworkId: `PARIS`
- From: `Location{STATION, stop_area:IDFM:63044, 48.7066360/2.4831850, place=Yerres, name=Yerres}`
- Via: `null`
- To: `Location{STATION, stop_area:IDFM:71572, 48.8297880/2.3767260, place=Quartier de la Gare, name=Bibliothèque François Mitterrand}`
- Date: `Tue Jan 17 16:14:43 GMT+01:00 2023`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:961)
android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
```

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
