### ISSUE TITLE
QUEBEC: java.lang.IllegalArgumentException: Unhandled error message: The region ca-qc doesn't exists

### ISSUE THREAD

**Issue by LindyStop** [schildbach/public-transport-enabler#515]
### Query
- NetworkId: `QUEBEC`
- From: `Location{ADDRESS, 45.5511240/-73.5465290, place=Montréal, name=Avenue Jeanne-D'arc 2329}`
- Via: `null`
- To: `Location{ADDRESS, 45.5505200/-73.5470360, place=Montréal, name=Avenue d'Orléans 2275}`
- Date: `Wed Jan 18 06:50:52 EST 2023`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error message: The region ca-qc doesn't exists
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1061)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
