### ISSUE TITLE
NEWYORK: java.lang.IllegalArgumentException: Unhandled error message: The region us-ny doesn't exists

### ISSUE THREAD

**Issue by adamnwork** [schildbach/public-transport-enabler#520]
### Query
- NetworkId: `NEWYORK`
- From: `Location{ADDRESS, 48.4403260/-123.3369740, place=Victoria, name=Ryan Street 1546}`
- Via: `null`
- To: `Location{COORD, -21.7026000/1.9590000}`
- Date: `Sun Feb 26 01:24:15 PST 2023`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error message: The region us-ny doesn't exists
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1061)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
