### ISSUE TITLE
SPAIN: java.lang.IllegalArgumentException: Unhandled error id: no_destination

### ISSUE THREAD

**Issue by pavelhr** [schildbach/public-transport-enabler#527]
### Query
- NetworkId: `SPAIN`
- From: `Location{STATION, stop_area:OOB:Navitia:109198, 41.2877670/2.0732240, place=el Prat de Llobregat, name=Terminal Aeroport T1}`
- Via: `null`
- To: `Location{POI, 41.6132920/2.6576100, name=Calella}`
- Date: `Fri Apr 21 15:32:07 GMT+02:00 2023`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error id: no_destination
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1065)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
