### ISSUE TITLE
Poland, java.lang.IllegalArgumentException: Unhandled error message: The region pl doesn't exists

### ISSUE THREAD

**Issue by dominmana** [schildbach/public-transport-enabler#528]
### Query
- NetworkId: `PLNAVITIA`
- From: `Location{ADDRESS, 50.3948310/16.5178610, place=Polanica-Zdrój, name=Warsvawska PL-02}`
- Via: `null`
- To: `Location{ADDRESS, 51.1403160/17.1966430, place=Kiełczów, name=Wrocławska PL-02, gmina Długołęka}`
- Date: `Fri Apr 21 15:30:25 GMT+02:00 2023`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error message: The region pl doesn't exists
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1061)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
I tried using Transportr and got the above error

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
