### ISSUE TITLE
BRITISHCOLUMBIA: java.lang.IllegalArgumentException: Unhandled error message: The region ca-bc doesn't exists

### ISSUE THREAD

**Issue by agdamsbo** [schildbach/public-transport-enabler#542]
### Query
- NetworkId: `BRITISHCOLUMBIA`
- From: `Location{ADDRESS, 49.2644110/-123.2453030, place=Electoral Area A, name=Wesbrook Mall}`
- Via: `null`
- To: `Location{ADDRESS, 49.2523920/-123.2458810, place=Electoral Area A, name=Trail 7 University of British Columbia}`
- Date: `Thu Aug 24 08:22:50 PDT 2023`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error message: The region ca-bc doesn't exists
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1061)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
Hi. I am on my Android with e/os/ 1.3 trying to look up trips in Vancouver, BC area.

**Comment by sk425** [comment]
Same issue for me

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
