### ISSUE TITLE
IT: java.lang.IllegalArgumentException: Unhandled error id: no_origin

### ISSUE THREAD

**Issue by airon90** [schildbach/public-transport-enabler#553]
### Query
- NetworkId: `IT`
- From: `Location{ADDRESS, 45.5656960/8.9064760, place=San Giorgio su Legnano, name=Via Monsignore Pietro Ermolli 4}`
- Via: `null`
- To: `Location{STATION, stop_area:OPC:Navitia:21307, 45.8165800/8.8326100, place=Varese, name=Varese, Trieste,stazione Fs}`
- Date: `Thu Jan 11 09:44:40 GMT+01:00 2024`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error id: no_origin
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1065)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
Every choice I make on Transportr the same error occurs

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
