### ISSUE TITLE
SPAIN: java.lang.IllegalArgumentException: Unhandled error id: no_origin

### ISSUE THREAD

**Issue by aaguilera** [schildbach/public-transport-enabler#572]
### Query
- NetworkId: `SPAIN`
- From: `Location{ADDRESS, 41.5273390/2.4339460, place=Mataró, name=Carrer de Tordera}`
- Via: `null`
- To: `Location{ADDRESS, 41.3881840/2.1153430, place=Barcelona, name=Carrer de Jordi Girona}`
- Date: `Tue Apr 30 19:22:26 GMT+02:00 2024`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error id: no_origin
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1065)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
