### ISSUE TITLE
Add New York, USA provider

### ISSUE THREAD

**Issue by anarcat** [schildbach/public-transport-enabler#84]
Just a feature request for now.. It seems that Navitia has the datasets for NY that we can use:

https://navitia.opendatasoft.com/explore/dataset/us-ny/

I am not sure how to make the necessary code happen here, but I'd love to see that happen, so just throwing this out there until I can find time / resources to actually learn how to implement this!

**Comment by schildbach** [comment]
You could use ParisProvider or ItalyProvider (or any other existing subclass of AbstractNavitiaProvider) as a template.

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
